# Base image
FROM python:3.11-slim

# Install system-level dependencies
RUN apt-get update && apt-get install -y \
  gcc \
  build-essential \
  python3-dev \
  libopenblas-dev \
  liblapack-dev \
  git \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy Python dependencies and install
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY app.py .
COPY utils.py .
COPY config.py .
COPY kafka_server_apis.py .
COPY models/ ./models
COPY data/extracted_ratings.csv ./data/
COPY experiments/ ./experiments
COPY evaluation/online_evaluation_output.txt ./evaluation/

# Expose Flask port
EXPOSE 8082

# Configure Git safe directory
RUN git config --global --add safe.directory /app

# Run Flask app
CMD ["gunicorn", "-w", "4", "-t", "120", "-b", "0.0.0.0:8082", "--access-logfile", "-", "--error-logfile", "-", "app:app"]
